/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nicolas.editorial;

import com.nicolas.editorial.controllers.EmpleadoImpl;
import com.nicolas.editorial.controllers.RevistaImpl;
import com.nicolas.editorial.controllers.SucursalImpl;
import com.nicolas.editorial.models.Empleado;
import com.nicolas.editorial.models.Revista;
import com.nicolas.editorial.models.Sucursal;
import com.nicolas.editorial.models.TmSucursal;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas
 */
public class SucursalesForm extends javax.swing.JFrame {

    /**
     * Creates new form SucursalesForm
     */
    
    private SucursalImpl impl;
    private EmpleadoImpl impl2;
    private RevistaImpl impl3;
    
    public SucursalesForm() {
        initComponents();
        this.setLocationRelativeTo(null); 
        mostrarSucursales();
        cargarEmpleados();
        cargarRevistas();
    }
    
    
    private void mostrarSucursales(){
        try {
            impl = new SucursalImpl();
            List<Sucursal> sucursales = impl.getAll();
            TmSucursal tm = new TmSucursal(sucursales);
            tblSucursales.setModel(tm); 
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", 
                    JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void cargarEmpleados(){
        try {
            impl2 = new EmpleadoImpl();
            List<Empleado> empleados = impl2.getAll();
            
            cboEmpleado.removeAllItems();
            
            for (Empleado e : empleados) {
                cboEmpleado.addItem(e); 
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", 
                    JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void cargarRevistas(){
        try {
            impl3 = new RevistaImpl();
            cboRevista.removeAllItems();
            
            for (Revista rev : impl3.getAll()) {
                cboRevista.addItem(rev); 
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", 
                    JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void limpiar(){
        txtTelefono.setText("");
        txtDomicilio.setText("");
        cboEmpleado.setSelectedIndex(0);
        cboRevista.setSelectedIndex(0); 
        
        txtTelefono.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboEmpleado = new javax.swing.JComboBox<>();
        cboRevista = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSucursales = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtDomicilioE = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 149, 188));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar una Sucursal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Mono", 0, 18), new java.awt.Color(56, 56, 57))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Telefono: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 79, 27));

        txtTelefono.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 272, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Domicilio: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 79, 27));

        txtDomicilio.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel1.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 272, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Empleado: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 27));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Revista:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 75, 27));

        cboEmpleado.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        cboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, -1));

        cboRevista.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        cboRevista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 270, -1));

        btnRegistrar.setText("Registrar Sucursal");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 360, -1));

        btnLimpiar.setText("Limpiar Datos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 360, -1));

        jTabbedPane1.addTab("Nueva", jPanel1);

        jPanel2.setBackground(new java.awt.Color(33, 42, 72));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Sucursales");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 12, 395, 34));

        tblSucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSucursales);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 614, 219));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Domicilio: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 70, 27));

        txtDomicilioE.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel2.add(txtDomicilioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, -1));

        btnEliminar.setText("Eliminar Sucursal");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 170, -1));

        jTabbedPane1.addTab("Ver registro", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtDomicilio.getText().trim().equalsIgnoreCase("") || 
                txtTelefono.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Complete TODOS los campos", 
                    "ADVERTENCIA", JOptionPane.WARNING_MESSAGE); 
        }else {
            try {
                String telefono, domicilio, dni_emp;
                int n_registro;
                telefono = txtTelefono.getText();
                domicilio = txtDomicilio.getText();
                Empleado emp = (Empleado) cboEmpleado.getSelectedItem();
                dni_emp = emp.getDni();
                Revista rev = (Revista) cboRevista.getSelectedItem();
                n_registro = rev.getN_registro();
                Sucursal suc = new Sucursal(telefono, domicilio, dni_emp, n_registro);
                impl.add(suc);
                
                JOptionPane.showMessageDialog(null, "Sucursal registrada", 
                    "INFO", JOptionPane.INFORMATION_MESSAGE); 
                
                mostrarSucursales();
                limpiar();
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), 
                    "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtDomicilioE.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el domicilio", 
                    "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            
            txtDomicilioE.requestFocus();
        }else {
            try {
                String domicilio = txtDomicilioE.getText();
                impl = new SucursalImpl();
                Sucursal suc = impl.getOne(domicilio);
                
                if (suc != null) {
                    impl.delete(suc.getDomicilio()); 
                    JOptionPane.showMessageDialog(null, "Sucursal eliminada", 
                    "INFO", JOptionPane.INFORMATION_MESSAGE);
                    
                    txtDomicilioE.setText(""); 
                    
                    mostrarSucursales();
                }else {
                    JOptionPane.showMessageDialog(null, "No se encontro la sucursal", 
                    "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), 
                    "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucursalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Object> cboEmpleado;
    private javax.swing.JComboBox<Object> cboRevista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblSucursales;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtDomicilioE;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
